### ISSUE TITLE
htaccess file

### ISSUE THREAD

**Issue by webmap2015** [cyclestreets/tilecache#10]
Hi, how can I create "htaccess" file like this "https://raw.githubusercontent.com/Raruto/tile-proxy-php/master/.htaccess" and delete "DOCUMENT_ROOT" in "https://raw.githubusercontent.com/cyclestreets/tilecache/master/index.php"

Thanks.

**Comment by mvl22** [comment]
I don’t understand the question. Can you clarify?

Are you reporting a bug?

**Comment by webmap2015** [comment]
This project (https://github.com/Raruto/tile-proxy-php) has "htaccess" file and it's working good and caching tiles.

![image](https://user-images.githubusercontent.com/10267317/77919568-05765480-72a6-11ea-957f-c4933f8311bc.png)


I run "https://github.com/cyclestreets/tilecache" project.
But, there is no cache folder or tiles. Only, I can view on the browser.

"http://localhost/tilecache-master/index.php?layer=mapnik&z=0&x=0&y=0"
![0](https://user-images.githubusercontent.com/10267317/77919358-bf20f580-72a5-11ea-80b9-5b658aed0915.png)

http://localhost/tilecache-master/index.php?layer=mapnik&z=0&x=0&y=5
![error](https://user-images.githubusercontent.com/10267317/77919370-c3e5a980-72a5-11ea-884d-b412331340ba.png)


I want to create "htaccess" file.

Thanks.

**Comment by mvl22** [comment]
You're referring to a different project, 'Raruto/tile-proxy-php', which is nothing to do with us.

If you need to create an .htaccess file, I recommend you search Google on how to do that.
https://www.google.com/search?q=creating+htaccess+file

**Comment by DirkR** [comment]
I suppose the original poster wants to setup this project in a folder of an existing web server and not as an vhost.

The correct answer is: Rename the file `.apache-vhost.conf.template` to `.htaccess` and remove everything except lines beginning with `Options`, `Rewrite...`, `ErrorDocument` and `header`.

Mine looks like this (I also added `RewriteBase /`):

```
Options -MultiViews

# Disable directory indexes
Options -Indexes

# Serve the tile directly if it exists; otherwise go through the cache
RewriteEngine On
RewriteBase /
RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} !-f
RewriteRule ^/([-a-z0-9]+)/([0-9]+)/([0-9]+)/(-?[0-9]+).png$ /index.php?action=tile&layer=$1&x=$3&y=$4&z=$2 [L,QSA]
RewriteRule ^/([-a-z0-9]+)/([0-9]+)/([0-9]+)/(-?[0-9]+)@([.0-9]+)x.png$ /index.php?action=tile&layer=$1&x=$3&y=$4&z=$2&scale=$5 [L,QSA]
RewriteRule ^/([-a-z0-9]+)/([-/a-z0-9]+)/([0-9]+)/([0-9]+)/(-?[0-9]+).png$ /index.php?action=tile&layer=$1&variant=$2&x=$4&y=$5&z=$3 [L,QSA]
RewriteRule ^/([-a-z0-9]+)/([-/a-z0-9]+)/([0-9]+)/([0-9]+)/(-?[0-9]+)@([.0-9]+)x.png$ /index.php?action=tile&layer=$1&variant=$2&x=$4&y=$5&z=$3&scale=$6 [L,QSA]

# Set a low-bandwidth error message for 404
ErrorDocument 404 "404 Resource not found"

# Allow cross-site HTTP requests
Header set Access-Control-Allow-Origin "*"
```

It depends on your Apache config which statements are allowed in the `.htaccess` file.

This issue can be closed now. ;)

**Comment by webmap2015** [comment]
Thanks.
